name: Go

on:
  push:
  pull_request:

jobs:
  
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install moreutils
        run: apt get -y moreutils
          
      - name: Gofmt
        run: not gofmt -l . | grep .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Install cover
        run: go install golang.org/x/tools/cmd/cover@latest
        
      - name: cover
        run: go tool cover -func=c.out
