name: Go

on:
  push:
  pull_request:

jobs:
  
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

  gofmt:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Gofmt
        run: not gofmt -l . | grep .

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: go test -v ./...

  cover:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install cover
        run: go install golang.org/x/tools/cmd/cover@latest
      - name: cover
        run: go tool cover -func=c.out
